# Generated by Django 6.0.7 on 2026-07-18 22:23

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('thumbnail_url', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=100)),
                ('level', models.CharField(default='beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('tax_id', models.CharField(default='', max_length=50)),
                ('contact_name', models.CharField(default='', max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('socio', 'Socio')], default='socio', max_length=10)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_revision', 'En Revision'), ('aprobado', 'Aprobado'), ('contrato_pendiente', 'Contrato Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='solicitado', max_length=20)),
                ('certification_date', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.FloatField(default=10.0)),
                ('notes', models.TextField(default='')),
                ('why_partner', models.TextField(default='')),
                ('sales_approach', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('video_url', models.CharField(max_length=500)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('video_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='prm.course')),
            ],
            options={
                'ordering': ['video_order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('client_industry', models.CharField(default='', max_length=100)),
                ('estimated_value', models.FloatField(default=0.0)),
                ('status', models.CharField(default='necesita_acceso', max_length=50)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pendiente', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='prm.deal')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='prm.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProgress',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('progress_pct', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='prm.course')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='prm.partner')),
            ],
            options={
                'unique_together': {('partner', 'course')},
            },
        ),
    ]
