# Generated by Django 6.0.7 on 2026-07-19 18:16

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='title',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('question', models.JSONField(default=dict)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='prm.coursevideo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('selected_index', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='prm.partner')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='prm.coursevideo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prm.quizquestion')),
            ],
        ),
    ]
