# Generated by Django 6.0.7 on 2026-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0002_alter_course_description_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursevideo',
            options={'ordering': ['phase', 'day', 'video_order']},
        ),
        migrations.AddField(
            model_name='course',
            name='phase_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='phase',
            field=models.IntegerField(default=1),
        ),
    ]
