# Generated by Django 6.0.7 on 2026-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0003_alter_coursevideo_options_course_phase_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='google_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='provider',
            field=models.CharField(default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
