# Generated by Django 6.0.7 on 2026-07-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0004_google_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogress',
            name='completed_videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
