# Generated by Django 6.0.7 on 2026-07-25 01:40

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0005_add_completed_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('estimated_value', models.FloatField(default=0.0)),
                ('stage', models.CharField(choices=[('prospeccion', 'Prospección'), ('calificacion', 'Calificación'), ('demostracion', 'Demostración'), ('negociacion', 'Negociación'), ('cotizacion_enviada', 'Cotización enviada'), ('cierre_ganado', 'Cierre ganado'), ('cierre_perdido', 'Cierre perdido'), ('archivado', 'Archivado')], default='prospeccion', max_length=30)),
                ('probability', models.IntegerField(default=10)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='prm.partner')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
