# Generated by Django 6.0.7 on 2026-08-01 01:27

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0007_loginattempt_tokenblacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='estimated_value',
        ),
        migrations.AddField(
            model_name='course',
            name='pass_mark',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_course_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_questions_count',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='course',
            name='related_products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('tecnica', 'Técnica'), ('cumplimiento', 'Cumplimiento'), ('todas', 'Todas')], default='todas', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='channel_manager',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company_size',
            field=models.CharField(choices=[('<250', 'Menos de 250'), ('250-1000', '250 - 1.000'), ('1000-5000', '1.000 - 5.000'), ('>5000', 'Más de 5.000')], default='<250', max_length=10),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='conflict_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deal_owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='delivery_quarter',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('commit', 'Commit'), ('best_case', 'Best Case'), ('pipeline', 'Pipeline'), ('omitted', 'Omitted')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(choices=[('generada_partner', 'Generada por el partner'), ('asignada_aconso', 'Asignada por aconso'), ('recomendacion_cliente', 'Recomendación de cliente')], default='generada_partner', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('precio', 'Precio'), ('competencia', 'Competencia'), ('sin_presupuesto', 'Sin presupuesto'), ('proyecto_aplazado', 'Proyecto aplazado'), ('otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_steps',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='operation_mode',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('on_premises', 'On-Premises')], default='cloud', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('nuevo', 'Nuevo negocio'), ('ampliacion', 'Ampliación'), ('cross_sell', 'Cross-Sell')], default='nuevo', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='protection_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='scan_one_time_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partner',
            name='training_track',
            field=models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('tecnica', 'Técnica'), ('cumplimiento', 'Cumplimiento'), ('', 'Sin asignar')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('cualificada', 'Cualificada'), ('propuesta_enviada', 'Propuesta enviada'), ('negociacion', 'Negociación'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='registrada', max_length=30),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('associate', 'Associate'), ('professional', 'Professional'), ('expert', 'Expert')], max_length=20)),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('pending_update', 'Válido, actualización pendiente'), ('expired', 'Caducado')], default='valid', max_length=20)),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='prm.partner')),
            ],
            options={
                'ordering': ['-certified_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityEvent',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, default='', max_length=30)),
                ('to_stage', models.CharField(max_length=30)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='prm.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('certificate_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='prm.course')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
