# Generated by Django 6.0.7 on 2026-08-01 02:14

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0008_remove_opportunity_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizBankQuestion',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('question', models.JSONField(default=dict)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField(default=0)),
                ('correct_indices', models.JSONField(blank=True, default=list)),
                ('fill_answer', models.JSONField(blank=True, default=dict)),
                ('question_type', models.CharField(choices=[('single', 'Opción única'), ('multiple', 'Opción múltiple'), ('true_false', 'Verdadero/Falso'), ('fill', 'Rellenar')], default='single', max_length=20)),
                ('track', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='exam_questions_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='publicado', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_indices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='fill_answer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Opción única'), ('multiple', 'Opción múltiple'), ('true_false', 'Verdadero/Falso'), ('fill', 'Rellenar')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='selected_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='prm.course')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='prm.partner')),
            ],
            options={
                'unique_together': {('course', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(default=5)),
                ('comment', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='prm.course')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='prm.partner')),
            ],
            options={
                'unique_together': {('course', 'partner')},
            },
        ),
    ]
