# Generated by Django 6.0.7 on 2026-08-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0009_quizbankquestion_course_exam_questions_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
    ]
