# Generated by Django 6.0.7 on 2026-08-01 18:45

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0010_remove_course_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOnboarding',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('manual_steps', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='prm.partner')),
            ],
        ),
    ]
