# Generated by Django 6.0.7 on 2026-08-01 22:56

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0011_partneronboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=200)),
                ('contact_name', models.CharField(default='', max_length=200)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'User Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('invitado', 'Invitado'), ('activo', 'Activo'), ('desactivado', 'Desactivado')], default='invitado', max_length=20)),
                ('invite_token', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='prm.partner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
