# Generated by Django 6.0.7 on 2026-08-02 02:46

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0012_partneruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='mdf_budget_year',
            field=models.FloatField(default=5000.0),
        ),
        migrations.CreateModel(
            name='MdfRequest',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('campaign_type', models.CharField(choices=[('evento', 'Evento'), ('campaña_online', 'Campaña online'), ('trade_show', 'Trade show / Feria'), ('contenido', 'Creación de contenido'), ('otro', 'Otro')], default='evento', max_length=30)),
                ('description', models.TextField(default='')),
                ('requested_amount', models.FloatField(default=0.0)),
                ('approved_amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reportado', 'Reportado'), ('cerrado', 'Cerrado')], default='solicitado', max_length=20)),
                ('approval_notes', models.TextField(default='')),
                ('actual_spend', models.FloatField(blank=True, null=True)),
                ('report_notes', models.TextField(default='')),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdf_requests', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
