# Generated by Django 6.0.7 on 2026-08-02 03:00

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0013_partner_mdf_budget_year_mdfrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('category', models.CharField(choices=[('merchandising', 'Merchandising'), ('evento', 'Evento'), ('formacion', 'Formación'), ('descuento', 'Descuento'), ('otro', 'Otro')], default='merchandising', max_length=20)),
                ('points_cost', models.IntegerField(default=100)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_cost', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='points_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('onboarding', 'Onboarding completado'), ('deal_ganado', 'Oportunidad ganada'), ('certificacion', 'Certificación conseguida'), ('mdf_reportado', 'MDF reportado'), ('manual', 'Ajuste manual'), ('canje', 'Canje de recompensa')], default='manual', max_length=30)),
                ('note', models.TextField(default='')),
                ('source_type', models.CharField(blank=True, default='', max_length=30)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('points_spent', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20)),
                ('admin_notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='prm.partner')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='prm.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
