# Generated by Django 6.0.7 on 2026-08-02 03:08

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0014_reward_partner_points_balance_partner_points_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConflict',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('en_resolucion', 'En resolución'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado sin resolución')], default='abierto', max_length=20)),
                ('notes', models.TextField(default='')),
                ('resolution', models.TextField(default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflicting_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_secondary', to='prm.opportunity')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_primary', to='prm.opportunity')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_conflicts', to='prm.partner')),
                ('winner_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_won', to='prm.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
