# Generated by Django 6.0.7 on 2026-08-02 03:14

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0015_channelconflict'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2026)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('admin_notes', models.TextField(default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to='prm.partner')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
                'unique_together': {('partner', 'year')},
            },
        ),
    ]
