# Generated by Django 6.0.7 on 2026-08-02 03:21

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0016_businessplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email')], default='in_app', max_length=20)),
                ('audience', models.CharField(choices=[('todos', 'Todos los partners'), ('seleccion', 'Partners seleccionados')], default='todos', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to='prm.partneruser')),
                ('target_partners', models.ManyToManyField(blank=True, related_name='targeted_communications', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='prm.communication')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('communication', 'partner')},
            },
        ),
    ]
