# Generated by Django 6.0.7 on 2026-08-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0017_communication_communicationrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to='prm.partner'),
        ),
    ]
