# Generated by Django 6.0.7 on 2026-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0018_alter_communication_sent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('key', models.CharField(help_text='Identificador único (slug), ej. dpa', max_length=60, primary_key=True, serialize=False)),
                ('name', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de }')),
                ('description', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de }')),
                ('category', models.CharField(default='core', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
    ]
