# Generated by Django 6.0.7 on 2026-08-08 14:16

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0020_seed_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('anuncio', 'Anuncio'), ('curso_nuevo', 'Curso nuevo'), ('curso_asignado', 'Curso asignado'), ('plan_negocio', 'Plan de negocio'), ('conflicto', 'Conflicto'), ('cuenta', 'Cuenta'), ('deal', 'Deal'), ('comunicacion', 'Comunicación')], default='anuncio', max_length=20)),
                ('title', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de }')),
                ('message', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de }')),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='prm.partner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'read'], name='prm_notific_partner_fdd35a_idx')],
            },
        ),
    ]
