# Generated by Django 6.0.7 on 2026-08-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0023_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='company_size',
            field=models.CharField(default='<250', max_length=30),
        ),
    ]
