# Generated by Django 6.0.7 on 2026-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0024_alter_opportunity_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dólar (USD)'), ('eur', 'Euro (EUR)'), ('chf', 'Franco suizo (CHF)'), ('otro', 'Otra moneda')], default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='custom_currency',
            field=models.CharField(blank=True, default='', help_text="Nombre de la moneda cuando currency='otro'", max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dólar (USD)'), ('eur', 'Euro (EUR)'), ('chf', 'Franco suizo (CHF)'), ('otro', 'Otra moneda')], default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_currency',
            field=models.CharField(blank=True, default='', help_text="Nombre de la moneda cuando currency='otro'", max_length=20),
        ),
    ]
