# Generated by Django 6.0.7 on 2026-08-24 18:31

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0026_product_multicurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('author_role', models.CharField(max_length=10)),
                ('author_name', models.CharField(default='', max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prm.businessplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
