# Generated by Django 6.0.7 on 2026-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0027_plancomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
