# Generated by Django 6.0.7 on 2026-08-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0028_businessplan_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancomment',
            name='plan',
        ),
        migrations.DeleteModel(
            name='BusinessPlan',
        ),
        migrations.DeleteModel(
            name='PlanComment',
        ),
    ]
