# Generated by Django 6.0.7 on 2026-08-25 16:06

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0029_remove_plancomment_plan_delete_businessplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExamQuestion',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('question', models.JSONField(default=dict)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField(default=0)),
                ('correct_indices', models.JSONField(blank=True, default=list)),
                ('question_type', models.CharField(choices=[('single', 'Opción única'), ('multiple', 'Opción múltiple'), ('true_false', 'Verdadero/Falso'), ('fill', 'Rellenar')], default='single', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions_custom', to='prm.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
