# Generated by Django 6.0.7 on 2026-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0030_add_course_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
