# Generated by Django 6.0.7 on 2026-09-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0031_partner_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostExportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de } - Document title')),
                ('subtitle', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de } - Subtitle / intro')),
                ('footer', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de } - Footer / notes')),
                ('product_col', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de } - Products column header')),
                ('annual_col', models.JSONField(blank=True, default=dict, help_text='Traducciones { en, es, de } - Annual license column header')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
