# Generated by Django 6.0.7 on 2026-09-04 15:16

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0032_costexportsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_quiz_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='VideoWatchEvent',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('watch_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='prm.partner')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='prm.coursevideo')),
            ],
            options={
                'unique_together': {('partner', 'video')},
            },
        ),
    ]
