# Generated by Django 6.0.7 on 2026-09-04 15:49

import django.db.models.deletion
import prm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0033_course_max_quiz_attempts_videowatchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCheckpoint',
            fields=[
                ('id', models.CharField(default=prm.models.gen_uuid, max_length=100, primary_key=True, serialize=False)),
                ('timestamp_seconds', models.FloatField()),
                ('question', models.JSONField(default=dict)),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField(default=0)),
                ('on_wrong_timestamp', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='prm.coursevideo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
