# Generated by Django 6.0.7 on 2026-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0034_videocheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('distribuidor', 'Distribuidor'), ('agente', 'Agente'), ('referidor', 'Referidor')], default='agente', max_length=20),
        ),
    ]
