# Generated by Django 6.0.7 on 2026-09-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prm', '0035_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('key', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('default_commission_rate', models.FloatField(default=10.0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(default='agente', max_length=60),
        ),
    ]
